FROM docker.io/centos

RUN yum install -y java-1.8.0-openjdk subversion maven && yum clean all -y
RUN wget https://www-us.apache.org/dist/tomcat/tomcat-9/v9.0.30/bin/apache-tomcat-9.0.30.zip

EXPOSE 9999
